### ISSUE TITLE
Crashes on sync

### ISSUE THREAD

**Issue by ihewitt** [ihewitt/poolviewer#8]
Incorrect pod type setting shows no error but causes crash on sync.
Any failure initialising new poda logic results in a crash and no error.

**Comment by jerome-labidurie** [comment]
A segfault happens when we click on "Sync watch" and no poolmate usb device is connected. (Original Pod selected in configuration)
It's coming from libusb_release_interface() called from poolmate_cleanup()
libusb_release_interface() seems to crash when dev->devh is NULL.

See https://github.com/jerome-labidurie/poolviewer/commit/6c548805ebb612a73268eb7584b93af23794baa0 for a simple correction.

**Comment by ihewitt** [comment]
aye, I added the bug to remind me to fix it! :)
Cheers,
Ivor

On Wednesday 24 Jun 2015 14:25:21 jerome-labidurie wrote:


A segfault happens when we click on "Sync watch" and no poolmate 
usb device is connected. (Original Pod selected in configuration)It's 
coming from libusb_release_interface() called from 
poolmate_cleanup()libusb_release_interface() seems to crash when 
dev->devh is NULL. 
See jerome-labidurie@6c54880[1] for a simple correction. 
—Reply to this email directly or view it on GitHub[2].[3]




--------
[1] https://github.com/jerome-labidurie/poolviewer/commit/6c548805ebb612a73268eb7584b93af237
94baa0
[2] 
https://github.com/ihewitt/poolviewer/issues/8#issuecomment-1150169
19
[3] 
https://github.com/notifications/beacon/AD3_LFbOvkUpR_SPiubviJDGC
ccjrqf_ks5oWxfBgaJpZM4D1wHa.gif

**Comment by ihewitt** [comment]
USB error conditions should now display messages rather than crashing.
